[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.0",
    "colorama>=0.4.6",
    "gitpython>=3.1.45",
    "pyyaml>=6.0.3",
    "questionary>=2.1.1",
    "rich>=14.1.0",
]
